name: Run pytest

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        icalendar-version:
          - "5.0"
          - "6.0"
          - "6.1"

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Set up Python 3.9"
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: "Install poetry"
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: 2.0.1

      - name: "Install icalendar ${{ matrix.icalendar-version }} and other dependencies"
        run: |
          poetry add icalendar~=${{ matrix.icalendar-version }}.0 --no-interaction

      - name: "Test with pytest"
        run: |
          poetry run coverage run test.py
          poetry run coverage xml

      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: false
